repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: no-commit-to-branch
        args: [--branch, master, --branch, stable]
    -   id: check-added-large-files
        args: [--maxkb=65536]
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: debug-statements
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-use-type-annotations
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: python-check-mock-methods
    -   id: python-no-log-warn
    -   id: text-unicode-replacement-char
    -   id: rst-backticks
    -   id: rst-directive-colons
    -   id: rst-inline-touching-normal
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        require_serial: true
    -   id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
    -   id: isort
        name: isort
        entry: isort
        require_serial: true
        language: system
        types: [python]
        args: ['--filter-files']
    -   id: black
        name: black
        entry: black
        language: system
        require_serial: true
        types: [python]
